from sqlalchemy import Column, Integer, String, Date
from app.core.database import Base

class TBL_CAF_Solicitud(Base):
    __tablename__ = "TBL_CAF_Solicitud"

    id_solicitud = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    Tipo_Contratacion = Column(String(100), nullable=True)
    Responsable = Column(String(100), nullable=True)
    Fecha = Column(Date, nullable=True)
    Cliente = Column(String(100), nullable=True)
    Building = Column(String(100), nullable=True)
    Direccion = Column(String(100), nullable=True)
    Proveedor = Column(String(100), nullable=True)
    Descripcion_trabajo_servicio = Column(String(100), nullable=True)
    Fecha_inicio = Column(Date, nullable=True)
    FechaTerminacionFinalServ = Column(Date, nullable=True)
    MontoMXNsubtotal = Column(String(100), nullable=True)
    MontoUSDsubtotal = Column(String(100), nullable=True)
    TDC = Column(String(100), nullable=True)
    Anticipo = Column(String(100), nullable=True)
    Fuerza_trabajo = Column(String(100), nullable=True)
    Presupuesto_existente = Column(String(100), nullable=True)
    Tipo_trabajo = Column(String(100), nullable=True)
    Recuperable = Column(String(100), nullable=True)
    Justificacion_trabajo = Column(String(100), nullable=True)
    Enlace_sharepoint = Column(String(1000), nullable=True)
    approve = Column(Integer, nullable=True)
    Cotizacion_MPA_CP = Column(Integer, nullable=True)
    AprobacionCorreoConcurso = Column(Integer, nullable=True)
    AnalisisRiesgosWHSE_VOBO = Column(Integer, nullable=True)
    DibujosEspecificaciones = Column(Integer, nullable=True)
    ProgramaObra = Column(Integer, nullable=True)
    DocumentoFirmar = Column(Integer, nullable=True)
    Acta_Constitutiva = Column(Integer, nullable=True)
    Poder_Notarial = Column(Integer, nullable=True)
    INE_Rep_Legal = Column(Integer, nullable=True)
    AltaIMSS_REPSE = Column(Integer, nullable=True)
    InfoBancariaContrato = Column(Integer, nullable=True)
    FichaPago = Column(Integer, nullable=True)
    InfoBancariaPagoDep = Column(Integer, nullable=True)
    Fecha_Ocupacion_Benefica = Column(Date, nullable=True)
    Fecha_Terminacion_Sustancial = Column(Date, nullable=True)
    Fianza_Anticipo = Column(String(100), nullable=True)
    FianzaCumplimiento_BuenaCalidad = Column(String(100), nullable=True)
    Fianza_Pasivos_Contingentes = Column(String(100), nullable=True)
    CveSol = Column(String(100), nullable=True)
    VOBO_LegalFirma = Column(Integer, nullable=True)
    VOBO_LegalPagoDep = Column(Integer, nullable=True)
    FechaTerminacionFinalCont = Column(Date, nullable=True)
    MontoOriginalMXN = Column(String(100), nullable=True)
    Comentarios = Column(String(500), nullable=True)
    Mode = Column(String(100), nullable=True)
    Usuario = Column(String(100), nullable=True)
    MontoOriginalUSD = Column(String(100), nullable=True)
    MontoActualizadoMXN = Column(String(100), nullable=True)
    MontoActualizadoUSD = Column(String(100), nullable=True)
    NuevaOcupacionBenefica = Column(String(100), nullable=True)
    NuevaTerminacionSust = Column(String(100), nullable=True)
    NuevaTerminacionFinal = Column(String(100), nullable=True)
    TiempoDias = Column(String(100), nullable=True)
